service: cvs-svc-trailer-registration

provider:
  name: aws
  runtime: nodejs12.12
  stage: dev
  tracing: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-tracing

functions:
  trailerId:
    handler: src/handler.handler

custom:
  serverless-offline:
    port: 3010
