service: cvs-svc-trailer-registration
useDotenv: true

# Create an optimized package for our functions 
package:
  individually: true
  exclude:
    - node_modules/**/*
  include:
    handler.ts


plugins:
  - serverless-webpack
  # - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    # https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
    shouldStartNameWithService: true
  # stage: ${env:STAGE}
  # region: ${env:AWS_REGION}
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  # environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
custom:
    webpack:
      # webpackConfig: 'webpack.config.js'
      includeModules: false   # Node modules configuration for packaging
      packager: 'npm'   # Packager that will be used to package your external modules
      excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
