# https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/functions.md
service: cvs-svc-trailer-registration
# Create an optimized package for our Functions
# This file has 2 purposes:
# - used to mock API Gateway so that we can work locally (with serverless-offline)
# - use webpack to bundle our code
package:
  individually: true
  exclude:
    - node_modules/**
    - .build/**
  include:
    - src/handler.ts

plugins:
  # https://github.com/serverless-heaven/serverless-webpack/tree/master/examples
  - serverless-dynamodb-local
  # https://github.com/serverless-heaven/serverless-webpack#usage-with-serverless-offline
  - serverless-offline

provider:
  profile: ${env:AWS_PROVIDER_PROFILE, 'default'}
  name: aws
  runtime: nodejs18.x
  apiGateway:
    # https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
    shouldStartNameWithService: true
  stage: ${env:AWS_PROVIDER_STAGE, 'local'}
  region: ${env:AWS_PROVIDER_REGION, 'eu-west-2'}
  environment:
    SERVICE_VERSION: ${env:API_VERSION}
    AWS_PROVIDER_REGION: ${self:provider.region}
    SERVICE: trailers

functions:
  # Use express routing so we don't rely on APIG and leverage express API
  app:
    handler: src/handler.handler
    events:
      - http: ANY /
      # We will proxy version from here in the client to match the API specs e.g. <stage>/**/*/<service>
      - http: 'ANY /{proxy+}'
  # Can also define specific functions on exposed routes using pattern matching, see below as example:
  # handler.ts containing exported getHello function is exposed on path /hello
  # that you can test locally sls invoke local -f getHello -d '{"path": "hello"}' or with sls offline
  # getHello:
  #   handler: src/handler.getHello
  #   events:
  #     - http: 'GET /hello'
custom:
  serverless-offline:
    httpPort: 3020
    lambdaPort: 3021
  dynamodb:
    start:
      port: 8020
      inMemory: true
      migrate: true
      seed: true
      noStart: false
    seed:
      trailer-registration:
        sources:
          - table: cvs-local-trailer-registration
            sources: [./tests/resources/trailer-registration.json]
    stages:
      - local
      - dev
      - test

resources:
  Resources:
    TrailerRegistration:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-trailer-registration
        AttributeDefinitions:
          - AttributeName: vinOrChassisWithMake
            AttributeType: S
          - AttributeName: trn
            AttributeType: S
        KeySchema:
          - AttributeName: vinOrChassisWithMake
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: vinOrChassisWithMakeIndex
            KeySchema:
              - AttributeName: vinOrChassisWithMake
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'
          - IndexName: trnIndex
            KeySchema:
              - AttributeName: trn
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
