service: cvs-svc-trailer-registration

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  timeout: 60
  region: eu-west-1
  environment:
    BRANCH: local
    DDB_OFFLINE_ENDPOINT: http://localhost:8000
    AWS_ACCESS_KEY_ID: accessKeyId
    AWS_SECRET_ACCESS_KEY: secretAccessKey

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      dev:
        sources:
          - table: cvs-${self:provider.environment.BRANCH}-trailer-registration
            sources: [./tests/resources/trailer-registration.json]

resources:
  Resources:
    TrailerRegistration:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-${self:provider.environment.BRANCH}-trailer-registration
        AttributeDefinitions:
          - AttributeName: vinOrChassisWithMake
            AttributeType: S
          - AttributeName: trn
            AttributeType: S
        KeySchema:
          - AttributeName: vinOrChassisWithMake
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: vinOrChassisWithMakeIndex
            KeySchema:
              - AttributeName: vinOrChassisWithMake
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'
          - IndexName: trnIndex
            KeySchema:
              - AttributeName: trn
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb
  - serverless-offline